[project]
name = "main"
version = "0.1.0"
requires-python = "~=3.12"
dependencies = [
    "dagger-io",
    "jinja2>=3.1.4",
    "toml>=0.10.2",
]

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"
